#!/bin/bash


xterm -T "A" -e python3 LinkStateRouting.py configA.txt &
xterm -T "B" -e python3 LinkStateRouting.py configB.txt &
xterm -T "C" -e python3 LinkStateRouting.py configC.txt &
xterm -T "D" -e python3 LinkStateRouting.py configD.txt &
xterm -T "E" -e python3 LinkStateRouting.py configE.txt &
xterm -T "F" -e python3 LinkStateRouting.py configF.txt 
